[
  {
    "url": "https://api.github.com/repos/quarnster/SublimeClang/issues/comments/9832706",
    "html_url": "https://github.com/quarnster/SublimeClang/issues/148#issuecomment-9832706",
    "issue_url": "https://api.github.com/repos/quarnster/SublimeClang/issues/148",
    "id": 9832706,
    "user": {
      "login": "quarnster",
      "id": 1230389,
      "avatar_url": "https://secure.gravatar.com/avatar/10a89302c6736c988ce06d8a41c923c0?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "gravatar_id": "10a89302c6736c988ce06d8a41c923c0",
      "url": "https://api.github.com/users/quarnster",
      "html_url": "https://github.com/quarnster",
      "followers_url": "https://api.github.com/users/quarnster/followers",
      "following_url": "https://api.github.com/users/quarnster/following",
      "gists_url": "https://api.github.com/users/quarnster/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/quarnster/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/quarnster/subscriptions",
      "organizations_url": "https://api.github.com/users/quarnster/orgs",
      "repos_url": "https://api.github.com/users/quarnster/repos",
      "events_url": "https://api.github.com/users/quarnster/events{/privacy}",
      "received_events_url": "https://api.github.com/users/quarnster/received_events",
      "type": "User"
    },
    "created_at": "2012-10-27T05:06:43Z",
    "updated_at": "2012-10-27T05:06:43Z",
    "body": "If you could provide a minimal reproduction case, that would be helpful."
  },
  {
    "url": "https://api.github.com/repos/quarnster/SublimeClang/issues/comments/9835023",
    "html_url": "https://github.com/quarnster/SublimeClang/issues/148#issuecomment-9835023",
    "issue_url": "https://api.github.com/repos/quarnster/SublimeClang/issues/148",
    "id": 9835023,
    "user": {
      "login": "quarnster",
      "id": 1230389,
      "avatar_url": "https://secure.gravatar.com/avatar/10a89302c6736c988ce06d8a41c923c0?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "gravatar_id": "10a89302c6736c988ce06d8a41c923c0",
      "url": "https://api.github.com/users/quarnster",
      "html_url": "https://github.com/quarnster",
      "followers_url": "https://api.github.com/users/quarnster/followers",
      "following_url": "https://api.github.com/users/quarnster/following",
      "gists_url": "https://api.github.com/users/quarnster/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/quarnster/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/quarnster/subscriptions",
      "organizations_url": "https://api.github.com/users/quarnster/orgs",
      "repos_url": "https://api.github.com/users/quarnster/repos",
      "events_url": "https://api.github.com/users/quarnster/events{/privacy}",
      "received_events_url": "https://api.github.com/users/quarnster/received_events",
      "type": "User"
    },
    "created_at": "2012-10-27T12:25:43Z",
    "updated_at": "2012-10-27T12:25:43Z",
    "body": "Actually I don't need a repro case for the Extensive search after a successful extensive search. The results should probably be cached (and if there are several candidates, all candidates should be showed again in case the candidate chosen wasn't the one we wanted).\r\n\r\nAs for the definition/implementation being available immediately from one translation unit but not another, are you including the header where the function is defined in both translation units? SublimeClang isn't keeping a full project index (and as per #7, I have no intention on implementing full project indexing myself) so all operations are per translation unit."
  },
  {
    "url": "https://api.github.com/repos/quarnster/SublimeClang/issues/comments/9853364",
    "html_url": "https://github.com/quarnster/SublimeClang/issues/148#issuecomment-9853364",
    "issue_url": "https://api.github.com/repos/quarnster/SublimeClang/issues/148",
    "id": 9853364,
    "user": {
      "login": "kvb",
      "id": 56630,
      "avatar_url": "https://secure.gravatar.com/avatar/86e0f9ed89997e37a3eba37ed8903220?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "gravatar_id": "86e0f9ed89997e37a3eba37ed8903220",
      "url": "https://api.github.com/users/kvb",
      "html_url": "https://github.com/kvb",
      "followers_url": "https://api.github.com/users/kvb/followers",
      "following_url": "https://api.github.com/users/kvb/following",
      "gists_url": "https://api.github.com/users/kvb/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kvb/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kvb/subscriptions",
      "organizations_url": "https://api.github.com/users/kvb/orgs",
      "repos_url": "https://api.github.com/users/kvb/repos",
      "events_url": "https://api.github.com/users/kvb/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kvb/received_events",
      "type": "User"
    },
    "created_at": "2012-10-29T00:16:03Z",
    "updated_at": "2012-10-29T00:16:03Z",
    "body": "I agree with the cached results to address the Extensive search; that seems to make the most sense.\r\n\r\nI do have the header included in the module that is having the issue jumping to Def'n/Impl.  It's very strange because it seems to be an issue in only some modules while in others the same function can be found w/o the extensive search.  I'll try to build a repro case for this, but it is a rather tough situation to get into."
  },
  {
    "url": "https://api.github.com/repos/quarnster/SublimeClang/issues/comments/9863489",
    "html_url": "https://github.com/quarnster/SublimeClang/issues/148#issuecomment-9863489",
    "issue_url": "https://api.github.com/repos/quarnster/SublimeClang/issues/148",
    "id": 9863489,
    "user": {
      "login": "quarnster",
      "id": 1230389,
      "avatar_url": "https://secure.gravatar.com/avatar/10a89302c6736c988ce06d8a41c923c0?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "gravatar_id": "10a89302c6736c988ce06d8a41c923c0",
      "url": "https://api.github.com/users/quarnster",
      "html_url": "https://github.com/quarnster",
      "followers_url": "https://api.github.com/users/quarnster/followers",
      "following_url": "https://api.github.com/users/quarnster/following",
      "gists_url": "https://api.github.com/users/quarnster/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/quarnster/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/quarnster/subscriptions",
      "organizations_url": "https://api.github.com/users/quarnster/orgs",
      "repos_url": "https://api.github.com/users/quarnster/repos",
      "events_url": "https://api.github.com/users/quarnster/events{/privacy}",
      "received_events_url": "https://api.github.com/users/quarnster/received_events",
      "type": "User"
    },
    "created_at": "2012-10-29T11:43:11Z",
    "updated_at": "2012-10-29T11:43:11Z",
    "body": "I've found an issue that might be the same you're seeing. If the index_parse_options bit (1<<2)=4 is set (which is the default) for enabling the [precompiled preamble](http://clang.llvm.org/doxygen/group__CINDEX__TRANSLATION__UNIT.html#gab1e4965c1ebe8e41d71e90203a723fe9) support for faster translation unit reparsing, it seems you can no longer translate a source location to a cursor in the translation unit if the location is in a file that is now in the precompiled preamble.\r\n\r\nThe current goto implementation does a \"get cursor at position x then get implementation of that cursor\" where x is the function definition in the header. This no longer works after the unit has been reparsed, however the reverse operation works; \"for each implementation, get the definition\" and we can compare for the exact implementation that way."
  },
  {
    "url": "https://api.github.com/repos/quarnster/SublimeClang/issues/comments/9874067",
    "html_url": "https://github.com/quarnster/SublimeClang/issues/148#issuecomment-9874067",
    "issue_url": "https://api.github.com/repos/quarnster/SublimeClang/issues/148",
    "id": 9874067,
    "user": {
      "login": "quarnster",
      "id": 1230389,
      "avatar_url": "https://secure.gravatar.com/avatar/10a89302c6736c988ce06d8a41c923c0?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "gravatar_id": "10a89302c6736c988ce06d8a41c923c0",
      "url": "https://api.github.com/users/quarnster",
      "html_url": "https://github.com/quarnster",
      "followers_url": "https://api.github.com/users/quarnster/followers",
      "following_url": "https://api.github.com/users/quarnster/following",
      "gists_url": "https://api.github.com/users/quarnster/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/quarnster/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/quarnster/subscriptions",
      "organizations_url": "https://api.github.com/users/quarnster/orgs",
      "repos_url": "https://api.github.com/users/quarnster/repos",
      "events_url": "https://api.github.com/users/quarnster/events{/privacy}",
      "received_events_url": "https://api.github.com/users/quarnster/received_events",
      "type": "User"
    },
    "created_at": "2012-10-29T16:15:44Z",
    "updated_at": "2012-10-29T16:15:44Z",
    "body": "1.0.37 is up, please let me know if it fixed the issue with the goto def working from one translationunit but not another is gone or please try to provide a small sample that exhibits the problem."
  },
  {
    "url": "https://api.github.com/repos/quarnster/SublimeClang/issues/comments/9903873",
    "html_url": "https://github.com/quarnster/SublimeClang/issues/148#issuecomment-9903873",
    "issue_url": "https://api.github.com/repos/quarnster/SublimeClang/issues/148",
    "id": 9903873,
    "user": {
      "login": "kvb",
      "id": 56630,
      "avatar_url": "https://secure.gravatar.com/avatar/86e0f9ed89997e37a3eba37ed8903220?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "gravatar_id": "86e0f9ed89997e37a3eba37ed8903220",
      "url": "https://api.github.com/users/kvb",
      "html_url": "https://github.com/kvb",
      "followers_url": "https://api.github.com/users/kvb/followers",
      "following_url": "https://api.github.com/users/kvb/following",
      "gists_url": "https://api.github.com/users/kvb/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kvb/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kvb/subscriptions",
      "organizations_url": "https://api.github.com/users/kvb/orgs",
      "repos_url": "https://api.github.com/users/kvb/repos",
      "events_url": "https://api.github.com/users/kvb/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kvb/received_events",
      "type": "User"
    },
    "created_at": "2012-10-30T12:32:38Z",
    "updated_at": "2012-10-30T12:32:38Z",
    "body": "It looks like version 1.0.37 does _not_ fix the issue of goto def working in one TU but not another.  I've been trying to get a repro case together as I cannot share the code that currently have this issue, but I'm having a rather difficult time doing it.\r\n\r\nThe ExtensiveSearch Caching seems to be working well.  Thanks for that."
  },
  {
    "url": "https://api.github.com/repos/quarnster/SublimeClang/issues/comments/9981108",
    "html_url": "https://github.com/quarnster/SublimeClang/issues/148#issuecomment-9981108",
    "issue_url": "https://api.github.com/repos/quarnster/SublimeClang/issues/148",
    "id": 9981108,
    "user": {
      "login": "kvb",
      "id": 56630,
      "avatar_url": "https://secure.gravatar.com/avatar/86e0f9ed89997e37a3eba37ed8903220?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "gravatar_id": "86e0f9ed89997e37a3eba37ed8903220",
      "url": "https://api.github.com/users/kvb",
      "html_url": "https://github.com/kvb",
      "followers_url": "https://api.github.com/users/kvb/followers",
      "following_url": "https://api.github.com/users/kvb/following",
      "gists_url": "https://api.github.com/users/kvb/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kvb/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kvb/subscriptions",
      "organizations_url": "https://api.github.com/users/kvb/orgs",
      "repos_url": "https://api.github.com/users/kvb/repos",
      "events_url": "https://api.github.com/users/kvb/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kvb/received_events",
      "type": "User"
    },
    "created_at": "2012-11-01T14:05:04Z",
    "updated_at": "2012-11-01T14:05:04Z",
    "body": "@quarnster, just to update you on this issue, it seems to be that at the moment this issue was due to a user (me) configuration error.\r\n\r\nFor the modules (translation units?) that were having trouble finding the def'n or impl it appears to be due to clang not being able to find a standard mingw header (in my case it was time.h).  Part of the include chain for the modules that were having issues included a custom module that included via `#include <time.h>`.\r\n\r\nSo in my case it went something like this:\r\n\r\nBusted TU (def'n or impl not working):\r\n```\r\n#include \"customheade1.h\"\r\n#include \"customheade2.h\"\r\n#include \"rtcdriver.h\"\r\n.\r\n.\r\n.\r\n```\r\nthen `rtcdriver.h` looked something like this:\r\n```\r\n#include <time.h>\r\n```\r\n\r\nthis probably should've been a dead giveaway...\r\n```\r\npath/to/file/rtcdriver.h - Fatal - 'time.h' file not found\r\nDid you configure the include path used by clang properly?\r\nSee http://github.com/quarnster/SublimeClang for more details on how to configure SublimeClang.\r\n```\r\nthe only reason it wasn't because I do have one nagging CLang compile error having to do with not finding a particular module specific to my build system (IAR; this is for work).  But with this error it *seems* that the goto def'n/impl is working okay; it just failed miserably when time.h was missing.\r\n\r\nSo to fix this issue of it not finding `time.h`, I just add to add the following to my project settings for _sublimeclang_options_:\r\n\r\n```\r\n\"-isystem\", \"C:\\\\MinGW\\\\include\",\r\n```\r\nwith that in my project settings, everything at the moment seems to be working well.\r\n\r\n\r\n"
  },
  {
    "url": "https://api.github.com/repos/quarnster/SublimeClang/issues/comments/9989920",
    "html_url": "https://github.com/quarnster/SublimeClang/issues/148#issuecomment-9989920",
    "issue_url": "https://api.github.com/repos/quarnster/SublimeClang/issues/148",
    "id": 9989920,
    "user": {
      "login": "quarnster",
      "id": 1230389,
      "avatar_url": "https://secure.gravatar.com/avatar/10a89302c6736c988ce06d8a41c923c0?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "gravatar_id": "10a89302c6736c988ce06d8a41c923c0",
      "url": "https://api.github.com/users/quarnster",
      "html_url": "https://github.com/quarnster",
      "followers_url": "https://api.github.com/users/quarnster/followers",
      "following_url": "https://api.github.com/users/quarnster/following",
      "gists_url": "https://api.github.com/users/quarnster/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/quarnster/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/quarnster/subscriptions",
      "organizations_url": "https://api.github.com/users/quarnster/orgs",
      "repos_url": "https://api.github.com/users/quarnster/repos",
      "events_url": "https://api.github.com/users/quarnster/events{/privacy}",
      "received_events_url": "https://api.github.com/users/quarnster/received_events",
      "type": "User"
    },
    "created_at": "2012-11-01T18:13:22Z",
    "updated_at": "2012-11-01T18:13:22Z",
    "body": "@kvb, Ok thanks for the update. Closing issue as I don't think there are any outstanding issues to fix here, please let me know if I'm misstaken and missed something."
  }
]
