[
  {
    "url": "https://api.github.com/repos/quarnster/SublimeClang/issues/comments/6432063",
    "html_url": "https://github.com/quarnster/SublimeClang/issues/74#issuecomment-6432063",
    "issue_url": "https://api.github.com/repos/quarnster/SublimeClang/issues/74",
    "id": 6432063,
    "user": {
      "login": "quarnster",
      "id": 1230389,
      "avatar_url": "https://secure.gravatar.com/avatar/10a89302c6736c988ce06d8a41c923c0?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "gravatar_id": "10a89302c6736c988ce06d8a41c923c0",
      "url": "https://api.github.com/users/quarnster",
      "html_url": "https://github.com/quarnster",
      "followers_url": "https://api.github.com/users/quarnster/followers",
      "following_url": "https://api.github.com/users/quarnster/following",
      "gists_url": "https://api.github.com/users/quarnster/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/quarnster/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/quarnster/subscriptions",
      "organizations_url": "https://api.github.com/users/quarnster/orgs",
      "repos_url": "https://api.github.com/users/quarnster/repos",
      "events_url": "https://api.github.com/users/quarnster/events{/privacy}",
      "received_events_url": "https://api.github.com/users/quarnster/received_events",
      "type": "User"
    },
    "created_at": "2012-06-19T17:37:27Z",
    "updated_at": "2012-06-19T17:37:27Z",
    "body": "Thanks for bringing this to my attention. I think it's a general Windows issue as it won't let you replace a dll that is in use. As to where the solution lies, I'm not really sure. If a dll loaded by a python plugin gets unloaded when the python references to it is garbage collected, then Package Control would have to be changed to remove all .py files first to force the unload and then do the update. But if the dll is still loaded even when all references are deleted, I'm not sure what if anything can be done.\n\nIf anyone have any suggestions here or knows the details of how the dll loading/unloading bits of python on Windows works I'd appreciate your input. Otherwise I'll look into this as time allows."
  },
  {
    "url": "https://api.github.com/repos/quarnster/SublimeClang/issues/comments/6531999",
    "html_url": "https://github.com/quarnster/SublimeClang/issues/74#issuecomment-6531999",
    "issue_url": "https://api.github.com/repos/quarnster/SublimeClang/issues/74",
    "id": 6531999,
    "user": {
      "login": "quarnster",
      "id": 1230389,
      "avatar_url": "https://secure.gravatar.com/avatar/10a89302c6736c988ce06d8a41c923c0?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "gravatar_id": "10a89302c6736c988ce06d8a41c923c0",
      "url": "https://api.github.com/users/quarnster",
      "html_url": "https://github.com/quarnster",
      "followers_url": "https://api.github.com/users/quarnster/followers",
      "following_url": "https://api.github.com/users/quarnster/following",
      "gists_url": "https://api.github.com/users/quarnster/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/quarnster/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/quarnster/subscriptions",
      "organizations_url": "https://api.github.com/users/quarnster/orgs",
      "repos_url": "https://api.github.com/users/quarnster/repos",
      "events_url": "https://api.github.com/users/quarnster/events{/privacy}",
      "received_events_url": "https://api.github.com/users/quarnster/received_events",
      "type": "User"
    },
    "created_at": "2012-06-24T10:54:37Z",
    "updated_at": "2012-06-24T10:55:41Z",
    "body": "I've taken a closer look at this and I don't think there's anything SublimeClang can do here. I reverted my windows install to a freshly installed state, installed sublimeclang via package control and then immediately uninstalled it again. This removed all python files (and thus all references to the dlls) but the dlls are still loaded it seems.\n\nAll of this was without having any c/c++ files opened, or put in different words, there would be no actual calls into neither libcache nor libclang, only the loading of these dll's and getting references to the functions.\n\nI had a look around the net if there's some kind of \"on\\_unload\" event or something I could use, but the closest I've found is to implement a class with a \"\\_\\_del\\_\\_\" function called on garbage collection. However there's no guarantee that this is run when needed, and also I couldn't find any sort of unload functionality in the [ctypes](http://docs.python.org/library/ctypes.html) python module anyway. I would have expected the ctypes object created when loading the library would also unload the library when that ctypes object is garbage collected, but that doesn't seem to be the case.\n\nSo I think this needs to be solved in Package Control when it notices that it can't replace a dll, it'll have to temporarily disable that package, prompt the user to restart Sublime Text 2 and on the next startup install the package properly and re-enable it now that the dlls have been updated. I've opened [issue 147](https://github.com/wbond/sublime_package_control/issues/147) on Package Control for this.\n\nClosing this issue. Please reopen if you find there's something that can be done SublimeClang side."
  },
  {
    "url": "https://api.github.com/repos/quarnster/SublimeClang/issues/comments/9840952",
    "html_url": "https://github.com/quarnster/SublimeClang/issues/74#issuecomment-9840952",
    "issue_url": "https://api.github.com/repos/quarnster/SublimeClang/issues/74",
    "id": 9840952,
    "user": {
      "login": "liang456",
      "id": 1673318,
      "avatar_url": "https://secure.gravatar.com/avatar/bf75ed46f2034fe6cc1075ce888084d8?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "gravatar_id": "bf75ed46f2034fe6cc1075ce888084d8",
      "url": "https://api.github.com/users/liang456",
      "html_url": "https://github.com/liang456",
      "followers_url": "https://api.github.com/users/liang456/followers",
      "following_url": "https://api.github.com/users/liang456/following",
      "gists_url": "https://api.github.com/users/liang456/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/liang456/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/liang456/subscriptions",
      "organizations_url": "https://api.github.com/users/liang456/orgs",
      "repos_url": "https://api.github.com/users/liang456/repos",
      "events_url": "https://api.github.com/users/liang456/events{/privacy}",
      "received_events_url": "https://api.github.com/users/liang456/received_events",
      "type": "User"
    },
    "created_at": "2012-10-27T23:17:39Z",
    "updated_at": "2012-10-27T23:17:39Z",
    "body": "Unfortunately, I encounter all most the same question, my ST2 2.01 even can not start. After I manully remove the SublimeCLang, I can restart the ST2.  Strange question."
  },
  {
    "url": "https://api.github.com/repos/quarnster/SublimeClang/issues/comments/9843066",
    "html_url": "https://github.com/quarnster/SublimeClang/issues/74#issuecomment-9843066",
    "issue_url": "https://api.github.com/repos/quarnster/SublimeClang/issues/74",
    "id": 9843066,
    "user": {
      "login": "quarnster",
      "id": 1230389,
      "avatar_url": "https://secure.gravatar.com/avatar/10a89302c6736c988ce06d8a41c923c0?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "gravatar_id": "10a89302c6736c988ce06d8a41c923c0",
      "url": "https://api.github.com/users/quarnster",
      "html_url": "https://github.com/quarnster",
      "followers_url": "https://api.github.com/users/quarnster/followers",
      "following_url": "https://api.github.com/users/quarnster/following",
      "gists_url": "https://api.github.com/users/quarnster/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/quarnster/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/quarnster/subscriptions",
      "organizations_url": "https://api.github.com/users/quarnster/orgs",
      "repos_url": "https://api.github.com/users/quarnster/repos",
      "events_url": "https://api.github.com/users/quarnster/events{/privacy}",
      "received_events_url": "https://api.github.com/users/quarnster/received_events",
      "type": "User"
    },
    "created_at": "2012-10-28T06:09:10Z",
    "updated_at": "2012-10-28T06:48:07Z",
    "body": "There's a [bug in ST2](http://www.sublimetext.com/forum/viewtopic.php?f=3&t=9825) where if an error message is shown before the main window has opened, the main window will never open on Windows. I'll include a work around for this issue in the next release."
  }
]
