[
  {
    "url": "https://api.github.com/repos/quarnster/SublimeClang/issues/comments/6821037",
    "html_url": "https://github.com/quarnster/SublimeClang/issues/89#issuecomment-6821037",
    "issue_url": "https://api.github.com/repos/quarnster/SublimeClang/issues/89",
    "id": 6821037,
    "user": {
      "login": "quarnster",
      "id": 1230389,
      "avatar_url": "https://secure.gravatar.com/avatar/10a89302c6736c988ce06d8a41c923c0?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "gravatar_id": "10a89302c6736c988ce06d8a41c923c0",
      "url": "https://api.github.com/users/quarnster",
      "html_url": "https://github.com/quarnster",
      "followers_url": "https://api.github.com/users/quarnster/followers",
      "following_url": "https://api.github.com/users/quarnster/following",
      "gists_url": "https://api.github.com/users/quarnster/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/quarnster/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/quarnster/subscriptions",
      "organizations_url": "https://api.github.com/users/quarnster/orgs",
      "repos_url": "https://api.github.com/users/quarnster/repos",
      "events_url": "https://api.github.com/users/quarnster/events{/privacy}",
      "received_events_url": "https://api.github.com/users/quarnster/received_events",
      "type": "User"
    },
    "created_at": "2012-07-07T06:38:27Z",
    "updated_at": "2012-07-07T06:38:27Z",
    "body": "I can reproduce when trying to complete in an unsaved file, this has been fixed by reapplying commit 5b8f515f999023d0943de2922bcd5c18d1955ed3 which for some reason had vanished, but I can't reproduce in a saved cpp file. Could you please retry after installing the latest version now?\n\nIf the crash still happens, could you please give me more details on how to reproduce the issue?"
  },
  {
    "url": "https://api.github.com/repos/quarnster/SublimeClang/issues/comments/7530484",
    "html_url": "https://github.com/quarnster/SublimeClang/issues/89#issuecomment-7530484",
    "issue_url": "https://api.github.com/repos/quarnster/SublimeClang/issues/89",
    "id": 7530484,
    "user": {
      "login": "quarnster",
      "id": 1230389,
      "avatar_url": "https://secure.gravatar.com/avatar/10a89302c6736c988ce06d8a41c923c0?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "gravatar_id": "10a89302c6736c988ce06d8a41c923c0",
      "url": "https://api.github.com/users/quarnster",
      "html_url": "https://github.com/quarnster",
      "followers_url": "https://api.github.com/users/quarnster/followers",
      "following_url": "https://api.github.com/users/quarnster/following",
      "gists_url": "https://api.github.com/users/quarnster/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/quarnster/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/quarnster/subscriptions",
      "organizations_url": "https://api.github.com/users/quarnster/orgs",
      "repos_url": "https://api.github.com/users/quarnster/repos",
      "events_url": "https://api.github.com/users/quarnster/events{/privacy}",
      "received_events_url": "https://api.github.com/users/quarnster/received_events",
      "type": "User"
    },
    "created_at": "2012-08-06T17:55:13Z",
    "updated_at": "2012-08-06T17:55:13Z",
    "body": "@knelson39 Is this still an issue?"
  },
  {
    "url": "https://api.github.com/repos/quarnster/SublimeClang/issues/comments/7853630",
    "html_url": "https://github.com/quarnster/SublimeClang/issues/89#issuecomment-7853630",
    "issue_url": "https://api.github.com/repos/quarnster/SublimeClang/issues/89",
    "id": 7853630,
    "user": {
      "login": "kblomqvist",
      "id": 206775,
      "avatar_url": "https://secure.gravatar.com/avatar/9a5a95217f9f0499ba809e47ca4333b4?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "gravatar_id": "9a5a95217f9f0499ba809e47ca4333b4",
      "url": "https://api.github.com/users/kblomqvist",
      "html_url": "https://github.com/kblomqvist",
      "followers_url": "https://api.github.com/users/kblomqvist/followers",
      "following_url": "https://api.github.com/users/kblomqvist/following",
      "gists_url": "https://api.github.com/users/kblomqvist/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kblomqvist/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kblomqvist/subscriptions",
      "organizations_url": "https://api.github.com/users/kblomqvist/orgs",
      "repos_url": "https://api.github.com/users/kblomqvist/repos",
      "events_url": "https://api.github.com/users/kblomqvist/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kblomqvist/received_events",
      "type": "User"
    },
    "created_at": "2012-08-19T14:35:14Z",
    "updated_at": "2012-08-19T14:39:51Z",
    "body": "I was managed to brick my ST2 installation. Had to manually remove this plugin and then restart the computer. Then I was able to start ST2 again. There wasn't any error messages. ST2 just didn't start."
  },
  {
    "url": "https://api.github.com/repos/quarnster/SublimeClang/issues/comments/8726496",
    "html_url": "https://github.com/quarnster/SublimeClang/issues/89#issuecomment-8726496",
    "issue_url": "https://api.github.com/repos/quarnster/SublimeClang/issues/89",
    "id": 8726496,
    "user": {
      "login": "quarnster",
      "id": 1230389,
      "avatar_url": "https://secure.gravatar.com/avatar/10a89302c6736c988ce06d8a41c923c0?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "gravatar_id": "10a89302c6736c988ce06d8a41c923c0",
      "url": "https://api.github.com/users/quarnster",
      "html_url": "https://github.com/quarnster",
      "followers_url": "https://api.github.com/users/quarnster/followers",
      "following_url": "https://api.github.com/users/quarnster/following",
      "gists_url": "https://api.github.com/users/quarnster/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/quarnster/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/quarnster/subscriptions",
      "organizations_url": "https://api.github.com/users/quarnster/orgs",
      "repos_url": "https://api.github.com/users/quarnster/repos",
      "events_url": "https://api.github.com/users/quarnster/events{/privacy}",
      "received_events_url": "https://api.github.com/users/quarnster/received_events",
      "type": "User"
    },
    "created_at": "2012-09-20T12:16:06Z",
    "updated_at": "2012-09-20T12:16:06Z",
    "body": "Closing bug as there's no reproduction steps and no one is complaining about it not being fixed ;)\n\nIf it happens again, please try launching Sublime Text 2 from within a debugger and see if you can get a stacktrace or any more information that might aid tracking the issue down."
  }
]
